INSERT INTO BIRDOGIE.USERS (username) VALUES ('petersongina');
INSERT INTO BIRDOGIE.USERS (username) VALUES ('frank31');
INSERT INTO BIRDOGIE.USERS (username) VALUES ('melissa70');
INSERT INTO BIRDOGIE.USERS (username) VALUES ('leblancjohn');
INSERT INTO BIRDOGIE.USERS (username) VALUES ('terrellscott');
INSERT INTO BIRDOGIE.USERS (username) VALUES ('misty84');
INSERT INTO BIRDOGIE.USERS (username) VALUES ('lisa47');
INSERT INTO BIRDOGIE.USERS (username) VALUES ('brendanorton');
INSERT INTO BIRDOGIE.USERS (username) VALUES ('rodney73');
INSERT INTO BIRDOGIE.USERS (username) VALUES ('patricia68');
INSERT INTO BIRDOGIE.POSTS (title, content, upvotes, downvotes, user_id) VALUES ('Space be view today approach.', 'Sometimes natural there can among now admit organization. Reality president everyone role by none job. Part during news training.', 24, 5, '6');
INSERT INTO BIRDOGIE.POSTS (title, content, upvotes, downvotes, user_id) VALUES ('Player both late behavior.', 'Close raise talk development. Sound consider you walk leave future.', 64, 23, '8');
INSERT INTO BIRDOGIE.POSTS (title, content, upvotes, downvotes, user_id) VALUES ('Occur story billion war dog.', 'Line benefit can system available staff your. Offer red cold recently wonder race world. Carry radio policy occur cost.', 86, 5, '1');
INSERT INTO BIRDOGIE.POSTS (title, content, upvotes, downvotes, user_id) VALUES ('Ability follow process million anyone space.', 'Challenge important again water poor property computer.', 86, 23, '1');
INSERT INTO BIRDOGIE.POSTS (title, content, upvotes, downvotes, user_id) VALUES ('Charge though still class spring.', 'Education drop despite move there research exist probably.', 73, 7, '2');
INSERT INTO BIRDOGIE.POSTS (title, content, upvotes, downvotes, user_id) VALUES ('Voice yes anyone word.', 'Knowledge student field follow my age just. Yard three experience according. Until well art role positive.', 69, 16, '8');
INSERT INTO BIRDOGIE.POSTS (title, content, upvotes, downvotes, user_id) VALUES ('Respond manager everyone our table.', 'Spend radio message morning mean itself contain. Imagine security away nice how represent. Politics responsibility yeah.', 34, 5, '5');
INSERT INTO BIRDOGIE.POSTS (title, content, upvotes, downvotes, user_id) VALUES ('Adult top result.', 'Receive move beat forget quickly police. Body attention tell rock task.', 77, 25, '8');
INSERT INTO BIRDOGIE.POSTS (title, content, upvotes, downvotes, user_id) VALUES ('Chair respond success network simple.', 'Show your attention well. Outside parent position although experience system effort measure.', 25, 1, '2');
INSERT INTO BIRDOGIE.POSTS (title, content, upvotes, downvotes, user_id) VALUES ('Night daughter unit.', 'Senior leave voice east attorney large.', 68, 29, '3');
INSERT INTO BIRDOGIE.POSTS (title, content, upvotes, downvotes, user_id) VALUES ('Relationship process sing idea what knowledge.', 'Cup model PM early wish difference. Common nor talk tree imagine send attention quickly.', 85, 24, '3');
INSERT INTO BIRDOGIE.POSTS (title, content, upvotes, downvotes, user_id) VALUES ('What which street one.', 'Despite available including right open both because fill. Our thought son whether community.', 39, 6, '1');
INSERT INTO BIRDOGIE.POSTS (title, content, upvotes, downvotes, user_id) VALUES ('Trouble character half plant president poor Mr.', 'Time or conference fund. Those social information be.', 63, 9, '10');
INSERT INTO BIRDOGIE.POSTS (title, content, upvotes, downvotes, user_id) VALUES ('Matter true compare network war save.', 'Discuss rich minute resource star. Republican road myself report democratic realize. Thank indeed care energy she.', 63, 30, '9');
INSERT INTO BIRDOGIE.POSTS (title, content, upvotes, downvotes, user_id) VALUES ('Win doctor exist on campaign out I.', 'Economy environmental might focus agent food. Marriage decision indicate while cut face. Available step necessary authority. Everyone bar no rather all.', 95, 19, '9');
INSERT INTO BIRDOGIE.POSTS (title, content, upvotes, downvotes, user_id) VALUES ('Crime current effort which nearly own not.', 'Entire over local be president trade. Word kid author play when south.', 46, 20, '8');
INSERT INTO BIRDOGIE.POSTS (title, content, upvotes, downvotes, user_id) VALUES ('Save billion magazine trade talk outside.', 'By simply care show station. Candidate hope he million a environment woman. Structure sometimes whom wear.', 63, 27, '4');
INSERT INTO BIRDOGIE.POSTS (title, content, upvotes, downvotes, user_id) VALUES ('Product give allow.', 'Into visit firm smile rest wall. Ago because contain guess black by west.', 48, 25, '5');
INSERT INTO BIRDOGIE.POSTS (title, content, upvotes, downvotes, user_id) VALUES ('Magazine value yes certain program wait blood.', 'Perform painting clear surface culture. Local at per network morning.', 20, 12, '10');
INSERT INTO BIRDOGIE.POSTS (title, content, upvotes, downvotes, user_id) VALUES ('Notice certain quite medical.', 'Discuss dark whose discuss history offer every. None employee item. Through five American something prepare trade their bag.', 11, 25, '7');
INSERT INTO BIRDOGIE.POSTS (title, content, upvotes, downvotes, user_id) VALUES ('Fire show study.', 'South admit eye soon concern. Until yeah president choice suffer yet memory. Its already boy per.', 45, 26, '10');
INSERT INTO BIRDOGIE.POSTS (title, content, upvotes, downvotes, user_id) VALUES ('Response sell couple.', 'Expect prepare up. Would poor own. Rich house parent outside long.', 29, 30, '4');
INSERT INTO BIRDOGIE.POSTS (title, content, upvotes, downvotes, user_id) VALUES ('Top quality follow all relationship.', 'Use government its wide director training win. Free store always off police true.', 46, 15, '5');
INSERT INTO BIRDOGIE.POSTS (title, content, upvotes, downvotes, user_id) VALUES ('Yard our use me.', 'Each size director night however over. Act care nor administration baby.', 31, 27, '10');
INSERT INTO BIRDOGIE.POSTS (title, content, upvotes, downvotes, user_id) VALUES ('In your ok action campaign.', 'Short they ever continue seat. Site mind score probably cup indicate. Friend create pattern information.', 57, 15, '1');
INSERT INTO BIRDOGIE.POSTS (title, content, upvotes, downvotes, user_id) VALUES ('Next moment writer administration sure.', 'Force mother rest. Social sing cut board. Blood family close arrive option remain such.', 38, 30, '10');
INSERT INTO BIRDOGIE.POSTS (title, content, upvotes, downvotes, user_id) VALUES ('Whether discuss view may.', 'Compare alone establish standard design range. Blue water consider land.', 55, 8, '1');
INSERT INTO BIRDOGIE.POSTS (title, content, upvotes, downvotes, user_id) VALUES ('Become see property between job.', 'Stock property imagine time. However work less really no right.', 57, 0, '5');
INSERT INTO BIRDOGIE.POSTS (title, content, upvotes, downvotes, user_id) VALUES ('Event dream key risk despite rise.', 'Consumer their scientist daughter source allow hot. Why wear either never risk.', 81, 2, '8');
INSERT INTO BIRDOGIE.POSTS (title, content, upvotes, downvotes, user_id) VALUES ('Choose fall away pattern black.', 'Sit participant why use possible. Tax understand current. Agree glass now specific floor think wait reality.', 71, 0, '3');
INSERT INTO BIRDOGIE.POSTS (title, content, upvotes, downvotes, user_id) VALUES ('Republican yard run light.', 'Staff responsibility nothing long force. Themselves parent consumer firm surface class explain.', 61, 1, '1');
INSERT INTO BIRDOGIE.POSTS (title, content, upvotes, downvotes, user_id) VALUES ('Expect sport plan girl couple such.', 'Others although would chair subject leader catch. Outside three different bill so. Those table spring because statement firm.', 42, 1, '4');
INSERT INTO BIRDOGIE.POSTS (title, content, upvotes, downvotes, user_id) VALUES ('Camera agree though cup us so happen.', 'Would compare break officer. Program author save consider.', 39, 5, '1');
INSERT INTO BIRDOGIE.POSTS (title, content, upvotes, downvotes, user_id) VALUES ('Grow director white piece.', 'Weight rock term still final. Care stay join particularly. Drug establish note soon.', 43, 27, '3');
INSERT INTO BIRDOGIE.POSTS (title, content, upvotes, downvotes, user_id) VALUES ('Particularly maybe back happy.', 'Right feeling opportunity lay right treat sit. Technology defense help miss like factor wife western. Project important certainly state final evidence.', 5, 26, '7');
INSERT INTO BIRDOGIE.POSTS (title, content, upvotes, downvotes, user_id) VALUES ('Car green no heart.', 'Across success thus first. High for different size business.', 8, 11, '7');
INSERT INTO BIRDOGIE.POSTS (title, content, upvotes, downvotes, user_id) VALUES ('Group ever fact pay a.', 'Thing sense drive item deep rather we. Situation training campaign candidate movement consumer. Practice record policy community study trade.', 23, 29, '8');
INSERT INTO BIRDOGIE.POSTS (title, content, upvotes, downvotes, user_id) VALUES ('Gas whatever bring bank.', 'Simple social learn poor language. Improve article recognize. Seven skin begin.', 80, 3, '8');
INSERT INTO BIRDOGIE.POSTS (title, content, upvotes, downvotes, user_id) VALUES ('May happen month western.', 'Avoid require many. Live should idea anyone discussion agree here.', 64, 16, '6');
INSERT INTO BIRDOGIE.POSTS (title, content, upvotes, downvotes, user_id) VALUES ('Lead employee including return game past free.', 'Mission several gun education figure environment. Make Congress within relationship memory possible go.', 95, 8, '8');
INSERT INTO BIRDOGIE.POSTS (title, content, upvotes, downvotes, user_id) VALUES ('Hand star performance central toward.', 'National instead determine decade nearly. Candidate local business difficult firm computer easy Mrs. Art me although determine now.', 7, 22, '3');
INSERT INTO BIRDOGIE.POSTS (title, content, upvotes, downvotes, user_id) VALUES ('Improve quite thus best step box agreement.', 'Treatment kid cost partner between nice. Carry security process hospital control.', 84, 8, '9');
INSERT INTO BIRDOGIE.POSTS (title, content, upvotes, downvotes, user_id) VALUES ('Democrat color young simple give suffer five.', 'Economy Mrs factor notice him wife day work. Expert assume still artist cause. Relate require oil economy discuss along near.', 93, 19, '4');
INSERT INTO BIRDOGIE.POSTS (title, content, upvotes, downvotes, user_id) VALUES ('Opportunity grow tax challenge mention detail dark.', 'Wrong million evidence such face. Meet bar according candidate dream still radio.', 81, 23, '9');
INSERT INTO BIRDOGIE.POSTS (title, content, upvotes, downvotes, user_id) VALUES ('Treatment watch however through writer down.', 'Friend race opportunity series activity. Water unit everybody strong view research news.', 81, 26, '7');
INSERT INTO BIRDOGIE.POSTS (title, content, upvotes, downvotes, user_id) VALUES ('Certain follow administration business.', 'Itself build agreement million. Reason interest tax technology. Anything goal take true behavior Congress debate sure.', 69, 10, '6');
INSERT INTO BIRDOGIE.POSTS (title, content, upvotes, downvotes, user_id) VALUES ('Plan exactly section each.', 'Law commercial rock threat. Every say phone forward political three.', 11, 1, '6');
INSERT INTO BIRDOGIE.POSTS (title, content, upvotes, downvotes, user_id) VALUES ('President cell discuss be arm while.', 'Lot institution law statement difference admit around paper. Expect positive degree little attack stand bank. Woman about cause stuff. Size bar suggest.', 32, 24, '8');
INSERT INTO BIRDOGIE.POSTS (title, content, upvotes, downvotes, user_id) VALUES ('Successful door floor scene break late writer hospital.', 'Tv best life nice how. Public today film research one ready phone. Human beat reach seem.', 100, 18, '5');
INSERT INTO BIRDOGIE.POSTS (title, content, upvotes, downvotes, user_id) VALUES ('Instead out professional wife born right now.', 'Other business it note work return. Effort list truth interesting. Woman kid prevent than author contain believe. Claim personal likely threat despite country character.', 11, 10, '2');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (1, 'Act which stand onto nearly seven dog system million education white cold.', 40, 2, '6');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (1, 'Window measure blue care star artist address.', 21, 10, '10');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (1, 'Discussion deal offer able which technology significant care will want.', 12, 20, '8');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (1, 'According chair eight single nation list condition hundred.', 4, 13, '2');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (1, 'These least anything across join west medical hour process activity including plant could.', 20, 0, '9');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (1, 'Feel quite management second number past future about.', 24, 13, '2');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (1, 'Attorney method another list carry official imagine student.', 1, 7, '1');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (1, 'Yes TV purpose risk game today culture hundred sometimes fight arm.', 15, 15, '7');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (1, 'House not age choice case action herself cost everything thing art citizen.', 36, 3, '5');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (2, 'Traditional manager buy drug hit significant student.', 14, 0, '10');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (2, 'Big again opportunity high I benefit certainly write interesting such.', 8, 12, '6');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (2, 'Put song possible speak between control.', 10, 7, '9');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (2, 'With reflect ability mouth area very participant coach commercial practice effect.', 12, 13, '9');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (2, 'Pretty teacher note rock energy million sometimes our out go reach people administration party.', 35, 18, '2');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (2, 'Operation great president agency age over spring decide.', 2, 13, '9');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (2, 'Better off the learn ok together especially.', 47, 6, '10');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (2, 'Very act do remain nature once evening edge.', 46, 15, '10');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (2, 'Seat once memory cost better whatever chance people decision need including upon.', 12, 7, '8');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (3, 'Man wide must off concern cold read.', 14, 17, '7');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (3, 'School than bed mouth sing than box road yet.', 32, 11, '8');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (3, 'Heart tough authority fast color summer thing right century in at month various.', 48, 5, '1');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (3, 'Cover network strategy spring enjoy give conference sound box.', 48, 12, '1');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (3, 'Health grow factor foreign around key edge conference.', 27, 5, '8');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (3, 'Fill party reveal space community fall note program.', 17, 17, '1');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (3, 'Financial risk out since character yourself beyond watch perhaps.', 11, 2, '1');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (4, 'Respond forget across ball we food size trip political several side.', 9, 14, '6');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (4, 'Left hear thousand father public indicate.', 36, 6, '3');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (4, 'Professor choice program future fine six its during market.', 3, 8, '7');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (4, 'Low education turn this party yard feeling cost.', 6, 8, '6');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (4, 'Beyond information dinner someone here bill century during kind kind message.', 31, 13, '4');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (4, 'Value remember most one similar deep force hope worry old inside whatever clearly.', 50, 1, '3');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (4, 'Meeting sense environmental forget far report maintain wall prevent.', 24, 8, '3');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (4, 'International top power wait amount stuff collection street actually.', 28, 1, '2');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (4, 'Growth it wind TV carry street growth oil all.', 3, 9, '8');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (4, 'Ready summer off huge seat away beat central health.', 41, 12, '1');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (5, 'Team here entire rock team carry family relate effort federal.', 47, 6, '4');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (5, 'Teach certainly arrive cold design off care center hair item theory.', 43, 11, '1');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (5, 'Market ever whether challenge turn west.', 0, 1, '3');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (5, 'Result open size boy price prepare movement themselves.', 39, 15, '8');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (5, 'Along protect rich red reflect smile service site field company ability.', 19, 16, '9');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (6, 'Hot especially artist large meeting central still window hand right rate under performance.', 19, 18, '5');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (6, 'Fly bank up stand attention night southern different nice executive billion interview own.', 23, 14, '6');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (6, 'Find choice step especially seem develop a usually.', 42, 19, '8');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (6, 'Effect end arm according because space real.', 13, 18, '1');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (6, 'Woman team democratic employee model win than where price name deep.', 16, 3, '1');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (6, 'Network understand bring experience relate moment large modern.', 15, 8, '3');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (6, 'Mr science goal model laugh sure economic lawyer still smile remember personal election.', 13, 8, '3');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (6, 'Nature short necessary learn probably performance drive front charge success thought cover front.', 34, 5, '2');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (6, 'Little relate major Mr issue information bed affect worry impact yet news.', 7, 8, '2');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (7, 'Inside language read process leader before home knowledge.', 15, 6, '6');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (7, 'Pretty reflect others film measure memory some establish.', 27, 3, '9');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (7, 'Another community organization care industry situation often word control return necessary treatment lawyer.', 8, 1, '10');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (7, 'Value discussion expect however actually modern table play toward attention order.', 12, 11, '3');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (7, 'Crime less place behind research reality every surface marriage friend upon.', 34, 4, '1');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (7, 'Question board blood above mean democratic buy early media.', 28, 14, '7');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (7, 'Give market real whole assume hope goal.', 28, 10, '3');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (7, 'Military just rock itself you in.', 32, 2, '5');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (8, 'So expect beautiful everything able board go drop black each.', 33, 19, '8');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (8, 'Table let speech society activity focus.', 46, 19, '6');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (8, 'System interview final garden recognize structure act benefit pay.', 28, 17, '10');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (8, 'Huge particularly allow suggest strategy effect think religious song join president those.', 21, 7, '2');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (8, 'While sure heart rule experience effect campaign maintain help sort behind.', 50, 10, '7');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (8, 'Very material word politics have firm our director game direction your beat.', 24, 18, '8');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (9, 'Individual reveal provide generation man who Mr scientist baby.', 49, 2, '7');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (9, 'Responsibility though evidence follow difficult camera painting air drop senior.', 25, 2, '2');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (9, 'Run note perform affect turn imagine too theory traditional page history suddenly.', 27, 11, '2');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (9, 'Might break alone today miss pay every none yes modern form.', 46, 20, '2');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (9, 'Dog push throughout population home sense heavy her.', 31, 11, '6');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (9, 'Citizen whether discuss speech list analysis similar tough.', 38, 1, '5');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (10, 'House house public north animal reveal.', 13, 7, '8');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (10, 'Threat shake agreement issue generation identify alone quality.', 38, 6, '3');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (10, 'Maybe energy yeah discuss music far arrive continue.', 34, 9, '2');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (10, 'Police know threat several politics save election name.', 39, 1, '1');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (10, 'Catch always indeed human option morning reach indeed baby above.', 20, 11, '1');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (11, 'Five ready unit performance what fund.', 37, 4, '8');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (11, 'Trip debate right popular whatever money resource response employee.', 12, 14, '3');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (11, 'Husband create sort protect new eight amount finally her.', 3, 12, '3');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (11, 'Act court argue ten tell style.', 41, 11, '9');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (11, 'Student strategy body finish specific friend although school matter respond cultural everyone.', 40, 8, '10');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (11, 'Red finally catch particularly entire cause raise mission between move.', 7, 2, '6');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (11, 'Cold indeed treat local good poor prevent.', 42, 6, '7');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (11, 'Statement certainly hand as out like.', 47, 8, '10');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (12, 'Design market chair miss computer organization.', 41, 19, '6');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (12, 'Chance party whole between fact audience stage stay sit office address music.', 27, 3, '6');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (12, 'Ok notice story then beat structure officer question according prepare thing new increase.', 7, 1, '5');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (12, 'Many view really prepare operation officer number number story capital bank friend TV.', 21, 10, '4');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (12, 'For different wide management whom attention identify feeling author resource appear.', 37, 15, '7');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (12, 'Arm voice than source whole effect little room once share cup store.', 33, 12, '9');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (12, 'Keep Republican mean fight red newspaper relate five sea economic president age artist.', 29, 20, '6');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (12, 'Eye raise something figure itself trial.', 31, 2, '8');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (12, 'Each Congress operation miss hour next long them education drive.', 16, 11, '9');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (13, 'Step how pick generation pull medical save many both per necessary federal.', 50, 3, '3');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (13, 'State collection building decide seven goal.', 34, 3, '6');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (13, 'Begin hundred today fight suddenly learn will product rich food white head.', 33, 9, '10');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (13, 'Fish take military almost environment lead various.', 37, 20, '6');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (13, 'Marriage still hand guess prevent in prevent international happen economic interview either key.', 5, 3, '2');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (13, 'Commercial style huge participant together theory chance key Mrs consumer.', 44, 10, '6');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (13, 'Test start suffer decision ever section cost high career computer hotel food.', 42, 13, '10');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (13, 'Person standard close attack million might customer activity you kitchen production chair.', 13, 12, '9');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (13, 'Evidence top approach senior have news hard.', 25, 13, '1');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (14, 'Think maybe letter ball deal discover property draw specific page where listen work head.', 47, 5, '6');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (14, 'Number factor something yeah a card trade.', 1, 13, '9');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (14, 'Better assume of dream first worry.', 27, 3, '7');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (14, 'Analysis account factor direction court key garden however modern best somebody.', 27, 11, '6');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (14, 'West get either area down write.', 25, 19, '1');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (14, 'Point kind sea then rise difficult identify.', 49, 1, '7');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (14, 'Television stay charge case try big born security former.', 18, 5, '1');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (14, 'Soldier foreign south tree statement Congress growth.', 6, 16, '3');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (14, 'Matter drop seven agree decide pattern also rule figure.', 35, 1, '1');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (14, 'Response right consider whose score memory why community car stuff across.', 18, 13, '5');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (15, 'Writer I probably paper similar very put subject major voice cup any.', 49, 3, '10');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (15, 'Staff always return listen trouble former.', 34, 6, '1');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (15, 'Machine economy new kitchen rock race believe.', 28, 4, '6');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (15, 'This simply peace sister nature worker.', 12, 1, '2');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (15, 'Stay affect hear organization site agreement there show information work movie for.', 18, 20, '2');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (15, 'Clear kind animal answer system pass guy people goal particular artist unit space.', 46, 14, '4');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (15, 'Compare social source public machine economy magazine.', 30, 18, '3');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (15, 'Color despite through hundred sit third bill.', 10, 4, '7');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (16, 'Wind rise approach term nature though sense.', 47, 11, '2');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (16, 'Claim break project stuff prove management usually role.', 49, 15, '2');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (16, 'Both say material kind have throughout student represent experience training stop very.', 15, 5, '8');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (16, 'Past within smile game nice tonight return skin check.', 11, 18, '3');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (16, 'Up son sound control reveal dinner person myself.', 20, 12, '9');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (16, 'Relationship result eight best parent would physical sea writer physical employee that once.', 22, 20, '9');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (16, 'Remember citizen that star environment series southern common bad factor Mr.', 22, 2, '2');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (16, 'Seem physical develop certainly word relate expert.', 32, 11, '7');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (16, 'Course house religious deal citizen fly material size.', 23, 0, '1');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (16, 'Cover teach onto ability after become scientist bag executive word.', 35, 0, '10');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (17, 'Nothing eye those head off right happen how.', 4, 19, '7');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (17, 'My blue fall nation drug decade never into heavy.', 0, 16, '3');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (17, 'Too alone scene management under social Democrat look.', 17, 19, '2');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (17, 'Eye reach almost might century nation glass area still part.', 30, 13, '8');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (17, 'Under history book teacher senior only because.', 22, 10, '8');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (17, 'Perform national future against remain thus action within.', 37, 8, '5');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (17, 'Case that mouth focus sell including crime it.', 46, 1, '3');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (18, 'Learn number money water message citizen.', 4, 2, '8');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (18, 'Sound surface election stage energy account.', 42, 8, '3');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (18, 'Cover nature cost design represent create discuss note.', 4, 8, '3');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (18, 'Democratic break red rest week tax knowledge save participant culture against.', 0, 4, '4');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (18, 'Throw may though quickly argue successful.', 47, 4, '10');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (18, 'Difference record reason painting politics view and matter friend grow right.', 13, 1, '10');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (18, 'Huge good white consider policy wear about.', 46, 8, '9');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (18, 'Fine west civil even almost option move include.', 48, 18, '4');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (18, 'Agent number town Congress allow animal American attack sure claim.', 17, 14, '3');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (19, 'Concern standard discuss recognize both democratic today national series book.', 14, 14, '1');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (19, 'Little body remember agreement skin south base.', 38, 1, '8');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (19, 'Rock site ability protect effort indicate would himself source company possible.', 50, 18, '5');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (19, 'Often hear figure woman eat religious.', 40, 14, '10');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (19, 'Church move Democrat play fall those evening series them single day left here.', 37, 0, '10');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (19, 'Money policy practice system forward good what always little middle summer degree.', 10, 9, '4');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (19, 'Save enjoy everyone be energy exist nearly civil.', 13, 10, '5');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (19, 'Difference sometimes very someone bring while TV.', 22, 8, '2');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (19, 'Something sign forward door opportunity movement.', 0, 7, '1');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (20, 'Administration moment keep book fight official candidate campaign wish treat capital environment must common.', 29, 13, '2');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (20, 'Make care through sister rate around opportunity like until.', 50, 18, '9');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (20, 'Factor need have eye whom size material our provide although consumer reveal carry.', 25, 16, '4');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (20, 'Military respond early wait father yeah mention play for little catch anyone.', 20, 8, '7');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (20, 'Medical land yet box special church more past.', 46, 14, '10');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (21, 'Southern everybody determine unit pick past young plant fly can.', 33, 16, '9');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (21, 'However take family article away thing three.', 32, 1, '4');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (21, 'Sell wrong mother bar action often type send.', 18, 13, '8');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (21, 'Hit institution listen collection now woman.', 28, 11, '9');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (21, 'A maintain prove power see help work plan marriage reveal.', 19, 16, '5');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (21, 'Of speech would environmental attention spend alone make high many attention ten go claim.', 3, 10, '2');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (22, 'Six his continue final story better whether direction discover watch study theory follow.', 1, 10, '9');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (22, 'Thought put enough forget but TV along goal wear design water.', 23, 8, '2');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (22, 'Door skill still likely create might perhaps myself sea will keep.', 33, 18, '7');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (22, 'Career shake daughter they job allow appear house race about.', 15, 19, '7');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (22, 'Clearly old charge ago total author pattern toward story recent development.', 29, 20, '5');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (22, 'Effect important own blood yes call list example explain.', 50, 15, '4');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (23, 'Other after big upon scene upon especially expect behavior nor situation.', 0, 7, '1');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (23, 'Remember eye listen gun wind range man ball set might give.', 8, 15, '6');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (23, 'Change mouth resource live guy production usually talk join window will article.', 29, 4, '1');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (23, 'Wife drug stand reveal act step experience future Mrs.', 36, 0, '6');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (23, 'Price series most poor lawyer money throw live water.', 26, 19, '8');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (23, 'Role camera other leg suddenly eat some box attention include.', 0, 9, '1');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (23, 'Small police seek report establish recently public office worker actually bring receive.', 0, 17, '1');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (24, 'Decade case wonder gas amount dream accept set increase hour scientist wish material.', 43, 5, '7');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (24, 'Color trade test more idea watch economy site myself there.', 7, 20, '3');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (24, 'How child eye note than tend take economy with later population out spend.', 15, 4, '5');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (24, 'Modern within offer maintain too rest focus subject very prepare relationship.', 25, 0, '10');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (24, 'Write hundred just manager instead ask drive country ok happy music call.', 13, 2, '7');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (24, 'Family per ago world shoulder firm fact source admit owner against.', 15, 20, '6');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (25, 'Table particular three look hear reach guy standard Democrat billion.', 44, 13, '8');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (25, 'Especially vote dream direction common woman today list cultural economic.', 48, 7, '2');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (25, 'Institution charge do social sort our participant college effect ready.', 31, 18, '2');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (25, 'Sense sound large weight hospital certain choice season far.', 2, 11, '6');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (25, 'Show car manage team collection population security compare.', 22, 13, '10');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (25, 'Role meeting woman also article couple buy course site seek future focus trial.', 3, 12, '6');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (25, 'Set office civil off very also movie lose personal focus.', 49, 0, '9');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (25, 'Determine pick human know authority than second prevent look compare tonight include ten truth.', 18, 0, '5');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (25, 'Report TV all name individual TV.', 50, 18, '9');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (25, 'Series artist memory simply carry follow study table western argue.', 13, 14, '7');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (26, 'Day throughout goal dark six voice young at.', 29, 12, '6');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (26, 'Office lose say scientist care some despite.', 10, 0, '3');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (26, 'Air into upon commercial realize item maintain enter or.', 38, 2, '8');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (26, 'Center test tonight finish thing return stop.', 17, 1, '2');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (26, 'Fund dog do last need cold unit task.', 25, 6, '1');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (27, 'Direction artist prevent result arm dinner relationship answer service cost able.', 32, 10, '6');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (27, 'Pattern particular sell low generation together exactly behavior federal sister.', 48, 3, '1');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (27, 'Five improve agree paper out detail mention across control century doctor key together.', 17, 19, '3');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (27, 'Kind born tree music member four sport social society personal call again.', 5, 17, '3');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (27, 'Guess couple soon tough almost road clearly night admit foot million type keep.', 45, 0, '9');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (27, 'Mind place action relate large energy loss popular pressure draw policy dinner still treatment.', 9, 8, '7');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (27, 'Exactly kitchen growth fast bring will message usually order after because out.', 9, 6, '8');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (27, 'Else event play size always later western answer little together international true even.', 15, 7, '2');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (28, 'Authority one whom strong stage seem forget security single still all call.', 38, 14, '7');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (28, 'Front need executive vote enjoy adult quality letter media message they environmental.', 31, 6, '4');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (28, 'Road choose management drive within senior.', 24, 0, '9');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (28, 'Nor add bag road analysis fact newspaper medical truth especially bed build.', 0, 18, '5');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (28, 'Establish think game military meeting official common wrong floor.', 0, 17, '4');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (28, 'Less child Mr style open in final cup ever build example.', 34, 3, '6');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (29, 'Behavior risk term foot night film future our expert defense dinner wait.', 36, 7, '10');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (29, 'Candidate loss mouth save walk always management last hundred.', 25, 20, '6');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (29, 'Couple play challenge operation understand serve join particularly type development audience truth night.', 20, 8, '4');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (29, 'Author scientist whatever natural that onto wear up figure to.', 18, 18, '8');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (29, 'Type practice follow institution box condition many situation huge growth the.', 41, 7, '3');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (29, 'Second trial good check table choice appear growth require southern the teach.', 28, 0, '3');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (29, 'Room only sure artist reveal show bill food.', 37, 11, '6');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (30, 'Visit process value public hit tree site receive daughter discuss himself upon.', 34, 14, '9');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (30, 'Build relate life white letter professor pressure successful.', 1, 14, '3');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (30, 'Window party behind method special affect many make read method structure hand.', 38, 0, '6');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (30, 'Few oil or instead add difference trouble.', 37, 4, '9');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (30, 'Investment hundred although region rock individual others current security various grow.', 16, 3, '6');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (30, 'Drop human executive now million hundred center.', 28, 19, '7');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (31, 'Human than area blue company word.', 32, 9, '5');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (31, 'Year door market where exactly be school itself.', 39, 2, '7');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (31, 'Sell make film share your line.', 4, 4, '8');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (31, 'Son respond various conference current too table person.', 36, 1, '10');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (31, 'What land shoulder before style risk weight relationship goal offer answer look statement.', 20, 20, '3');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (31, 'Write message class result strong which lawyer.', 25, 2, '3');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (31, 'Admit create above might great fish operation majority else dream.', 11, 19, '6');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (31, 'Budget late herself speech process last occur may edge.', 33, 5, '5');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (31, 'Little material fast artist case chance easy by.', 0, 17, '3');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (32, 'Note people include most various room stage option home.', 6, 6, '1');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (32, 'Deep group win major star side leader bad.', 36, 13, '7');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (32, 'Call market make three foot scene reduce they girl left mention physical.', 7, 8, '7');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (32, 'These young itself dinner treat media prepare live relate effect course technology design.', 20, 7, '2');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (32, 'Itself happy fund offer can lawyer term me so.', 44, 4, '5');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (32, 'Ever hospital too likely former so tell seat.', 43, 10, '4');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (32, 'Each else onto win meeting cover bed none election.', 0, 0, '9');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (32, 'Worry population explain least strong key brother life improve third account business.', 49, 20, '5');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (33, 'Mouth determine important special despite question.', 15, 5, '7');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (33, 'Across fine necessary arrive eat less baby chance visit establish Congress girl.', 20, 1, '9');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (33, 'Sell maybe low per nation next light officer discover energy defense.', 27, 15, '9');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (33, 'Matter full friend enjoy my relate defense seem everybody data without house.', 48, 11, '1');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (33, 'Provide another wait front rule especially statement phone.', 20, 9, '3');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (33, 'Generation process police level report rise operation thing bit sea buy near back.', 8, 12, '6');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (33, 'Task value budget purpose instead whether begin test six story while use notice.', 36, 17, '8');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (33, 'Their fast memory second Congress decide nice reason green affect.', 48, 10, '8');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (33, 'Of firm of unit walk under manage throw network media.', 25, 15, '2');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (33, 'Appear eye piece often bring him after something this.', 4, 8, '5');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (34, 'Result thing just various down southern space instead.', 9, 11, '4');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (34, 'Street customer five agency develop cell cup respond.', 17, 7, '1');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (34, 'Few family four level than professor think.', 1, 12, '4');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (34, 'Hear site including describe talk discover now end over safe worry.', 47, 6, '4');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (34, 'Activity north whom activity significant prevent simply event one.', 7, 17, '1');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (34, 'Ground car sort beyond exactly environmental section large.', 27, 12, '6');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (34, 'Nice threat inside certainly admit few realize leg power marriage school condition page.', 40, 5, '10');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (34, 'Help food read organization option message.', 45, 1, '5');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (34, 'Hit in range since nor note.', 6, 0, '1');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (35, 'Structure get sure reduce world much relationship suffer local rest.', 50, 3, '9');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (35, 'Control account great per hold do personal allow series free full new focus.', 40, 0, '10');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (35, 'Speech while my above finish force clearly join.', 0, 7, '3');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (35, 'Defense social fear continue treatment sister analysis.', 0, 14, '4');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (35, 'Base force family president hour manager.', 46, 17, '9');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (35, 'Step check sit dark serious yard score throughout push meet level.', 26, 0, '4');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (36, 'National part almost expect herself home hospital on century letter area.', 36, 0, '4');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (36, 'Fill indeed thousand important police piece write start too born.', 47, 20, '3');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (36, 'Wife customer tonight bill likely artist inside kid.', 32, 16, '3');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (36, 'Affect focus there impact never during type inside industry director TV look.', 14, 8, '10');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (36, 'Yourself brother friend voice animal suffer return really suddenly great.', 8, 20, '3');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (36, 'Power change fear relationship well store discover phone alone vote form.', 23, 10, '2');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (36, 'Scene rock scene head perform four support road up light weight.', 18, 2, '8');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (36, 'Fear shoulder sea purpose summer agency either there join style evidence nice direction.', 39, 3, '6');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (36, 'Most simple open play down material.', 37, 3, '3');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (37, 'Ago ask push idea moment admit yet.', 5, 5, '9');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (37, 'Pull floor least line conference almost lay skill get act few service scene.', 18, 10, '5');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (37, 'Customer instead be forward continue media statement commercial bit prepare then artist foreign.', 38, 7, '2');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (37, 'New herself enter meet box gun author thus small none one yet.', 19, 3, '7');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (37, 'Food guy opportunity short Mrs commercial.', 12, 16, '8');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (38, 'Although report guy attention consumer must out edge cover.', 11, 2, '9');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (38, 'Cell tend act material still far office baby left.', 29, 12, '7');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (38, 'Final million change friend move understand security east throughout entire instead.', 36, 4, '2');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (38, 'Start make address on specific military song trip cut throughout site head according.', 49, 8, '8');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (38, 'First amount agent range part author police wrong window speech.', 46, 9, '7');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (38, 'Bit still world beat natural race.', 24, 7, '4');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (38, 'Out main chance push leg east group.', 46, 7, '7');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (38, 'Social you ability available sense worker main material nearly cost only perform eye.', 5, 14, '8');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (39, 'Choose buy exist later customer rule big seem miss.', 49, 9, '5');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (39, 'Another market reality art news ball job current way.', 30, 13, '1');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (39, 'Fill hot watch assume way to analysis kitchen model ball like stop.', 46, 20, '2');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (39, 'Author watch religious reason hit station entire.', 44, 10, '1');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (39, 'Environment sort good agency anything professor effort under watch possible yes.', 33, 12, '6');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (39, 'Mother decision enter listen phone politics base.', 6, 13, '7');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (39, 'Week chance page gas animal recognize often.', 2, 18, '4');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (39, 'Concern grow growth wide only well family ok customer.', 47, 19, '5');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (39, 'Six rock sister final else different important relate guess development tend fear.', 25, 16, '5');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (40, 'Center speech early leave evening have data while.', 50, 20, '2');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (40, 'West story network indeed cup open about.', 29, 16, '3');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (40, 'Understand cup senior base build at.', 18, 0, '2');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (40, 'Film discuss campaign thus development thank later more.', 4, 20, '5');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (40, 'Produce employee Democrat cause together way rock worker hundred individual adult article plan us.', 45, 0, '1');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (40, 'Born suffer difference audience car available home operation myself miss crime present.', 0, 17, '1');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (40, 'Hard trade have finally fine admit science happen seven like.', 41, 7, '2');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (40, 'Congress write read imagine commercial also understand fear story consumer security away.', 32, 14, '8');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (40, 'Ready paper still too mention Mr skill stuff mouth agency manage reason marriage.', 17, 18, '2');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (41, 'Then notice case drop particularly early much involve at reason.', 46, 13, '8');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (41, 'Off Congress officer positive add edge near head available account writer.', 20, 2, '9');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (41, 'Strategy this accept early main general house glass thus red.', 29, 7, '7');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (41, 'Contain sound recognize edge senior Mrs yet goal toward better.', 24, 16, '2');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (41, 'Accept see military year something surface hot say.', 18, 3, '2');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (41, 'Instead last although Mr bag fill minute direction level sister season training others.', 6, 18, '4');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (41, 'Whether today structure author our dinner art husband TV color and.', 48, 11, '10');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (41, 'Because law believe common network walk ten close price Mr police home face.', 46, 14, '5');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (41, 'Simply space less respond thing adult economy nearly option create.', 45, 15, '9');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (42, 'Style attention class field participant low natural live trouble ability outside camera.', 49, 14, '2');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (42, 'Lawyer culture instead hand rest develop coach care level human hour.', 20, 9, '9');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (42, 'Friend include theory age nature enough other natural camera true open defense.', 5, 0, '7');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (42, 'Standard born magazine drop daughter ball matter control size born.', 43, 15, '3');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (42, 'Technology establish third certain lead on reach their build.', 6, 9, '10');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (42, 'Responsibility enter effect seem operation position.', 39, 15, '3');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (42, 'Someone left now section west product hot quality.', 37, 14, '9');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (42, 'Challenge for recognize civil officer attorney those.', 43, 19, '2');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (42, 'Kitchen prevent film court save writer rate social.', 12, 20, '9');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (42, 'Clearly side where really most crime.', 45, 10, '4');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (43, 'Within than author challenge interview least.', 22, 5, '5');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (43, 'Director poor reduce whom keep skin second top agency.', 10, 19, '8');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (43, 'Prepare full easy way ago my.', 46, 14, '6');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (43, 'What adult let per three right include business born.', 37, 7, '3');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (43, 'Few interview structure free drop law theory bill goal language indeed wear.', 17, 2, '6');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (44, 'Mean political story short product tonight.', 36, 19, '7');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (44, 'Throughout Mrs bed billion sound deal lead him bad.', 12, 16, '1');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (44, 'Face away Mr open factor less light company social respond door someone public.', 12, 8, '1');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (44, 'Him spring fight when sit development girl ten than practice college imagine real.', 16, 0, '8');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (44, 'Give job pull travel really executive certainly mention lot.', 32, 6, '2');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (44, 'Act when here kind artist use drop style popular.', 35, 16, '7');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (44, 'Culture authority few debate situation it ball change.', 10, 7, '4');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (45, 'Specific late quickly last finally interest interest treat every.', 20, 12, '10');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (45, 'Reason sing election yet best pass.', 13, 0, '4');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (45, 'Attorney federal we management full exist particular part clearly product story old on.', 29, 20, '5');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (45, 'For color effect wide fear capital.', 1, 17, '1');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (45, 'Thank maintain break themselves hot three others example run act blue degree fish.', 27, 9, '6');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (45, 'Work sister pick realize my president magazine lawyer paper.', 22, 10, '1');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (45, 'Require talk rise million door remember laugh leader boy wish.', 11, 8, '1');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (45, 'Reflect attention institution realize think tend ability bring act its place glass.', 2, 14, '1');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (45, 'Card left piece wife growth ability while bit big right.', 28, 16, '2');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (45, 'Energy our then than race sell red above west economy.', 36, 8, '7');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (46, 'Commercial particularly floor wonder quite wait clear information management.', 49, 14, '7');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (46, 'Deep eye play standard top measure.', 8, 2, '5');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (46, 'Information appear travel bit keep all stuff half.', 10, 15, '7');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (46, 'Instead politics when cup plan themselves structure girl certainly information.', 21, 10, '6');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (46, 'Man whether help late get act.', 16, 0, '8');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (46, 'See at shake send risk good cost.', 34, 8, '8');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (46, 'She have rich address difference point information speech.', 50, 2, '6');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (46, 'Himself ok game although of cultural choice far relationship black.', 5, 13, '4');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (46, 'Civil reach box quality this difficult to.', 13, 2, '1');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (47, 'Miss shake responsibility central it Mr care politics sometimes affect situation ground.', 41, 19, '9');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (47, 'No central benefit partner professional look strategy technology recent child customer dog.', 21, 11, '9');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (47, 'Rise attorney away son author leave style nothing.', 37, 5, '6');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (47, 'Health us evidence score man hope more one.', 22, 3, '3');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (47, 'Second artist reality peace arm near top size car him.', 18, 7, '4');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (47, 'Near summer tend involve ago thought.', 38, 0, '4');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (47, 'Thousand deal success second full well decide part summer bed answer rather.', 50, 1, '6');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (47, 'Look be cell around determine talk life majority tree himself on mission.', 23, 12, '10');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (48, 'Very however happen dream center fact.', 14, 0, '5');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (48, 'Professional require standard family little real education customer reason purpose debate describe power.', 19, 8, '1');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (48, 'Throw break modern training candidate near tend seat.', 2, 17, '1');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (48, 'According ask story name democratic from senior campaign decade among trade any.', 4, 8, '6');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (48, 'Firm option color yes car ability part service not too head professional class various.', 30, 7, '2');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (48, 'Administration least might phone decision threat nation plan.', 42, 16, '3');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (48, 'Arm story professor body kind think whose read red.', 36, 8, '4');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (48, 'Weight indeed challenge relate reduce provide operation nice.', 49, 2, '6');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (48, 'Understand sell event oil charge strategy three discuss future agent mission Republican.', 35, 13, '8');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (49, 'Next animal treat church reflect management area situation them yard say employee.', 11, 9, '2');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (49, 'Answer sell find third with enjoy want relate number thought sound newspaper perform.', 37, 11, '2');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (49, 'Debate scientist clearly church deep majority station rest.', 17, 0, '6');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (49, 'Dog shoulder my just religious may structure rock activity cut interesting.', 22, 0, '10');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (49, 'Yard future significant minute truth team.', 0, 16, '7');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (49, 'Room student reason product account family rate drive.', 25, 9, '5');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (49, 'Boy above company particular bed center federal price.', 35, 18, '2');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (49, 'When economic our account throw law would these.', 34, 3, '10');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (49, 'War perhaps after meet idea address no family end remain attack.', 3, 10, '5');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (49, 'Peace project store issue memory also source model community tax art.', 20, 17, '7');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (50, 'Imagine college different summer hand thus trouble system teach.', 31, 0, '9');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (50, 'Truth field language change skill indeed write treat.', 18, 20, '3');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (50, 'Group concern room a artist yes after early try after.', 6, 14, '4');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (50, 'Audience a as tree development relate middle over suddenly forget sure way director.', 2, 12, '5');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (50, 'Point medical specific environment level performance.', 10, 5, '8');
INSERT INTO BIRDOGIE.COMMENTS (post_id, content, upvotes, downvotes, user_id) VALUES (50, 'Kitchen heart maybe decide him measure commercial baby medical treatment information.', 34, 5, '7');
INSERT INTO BIRDOGIE.TAGS (post_id, tag_name) VALUES (1, 'Review');
INSERT INTO BIRDOGIE.TAGS (post_id, tag_name) VALUES (2, 'Beginner');
INSERT INTO BIRDOGIE.TAGS (post_id, tag_name) VALUES (2, 'Equipment');
INSERT INTO BIRDOGIE.TAGS (post_id, tag_name) VALUES (2, 'LIV');
INSERT INTO BIRDOGIE.TAGS (post_id, tag_name) VALUES (3, 'Rules');
INSERT INTO BIRDOGIE.TAGS (post_id, tag_name) VALUES (4, 'Tips');
INSERT INTO BIRDOGIE.TAGS (post_id, tag_name) VALUES (4, 'PGA Tour');
INSERT INTO BIRDOGIE.TAGS (post_id, tag_name) VALUES (4, 'Rules');
INSERT INTO BIRDOGIE.TAGS (post_id, tag_name) VALUES (5, 'PGA Tour');
INSERT INTO BIRDOGIE.TAGS (post_id, tag_name) VALUES (5, 'Korn Ferry');
INSERT INTO BIRDOGIE.TAGS (post_id, tag_name) VALUES (6, 'PGA Tour');
INSERT INTO BIRDOGIE.TAGS (post_id, tag_name) VALUES (6, 'Courses');
INSERT INTO BIRDOGIE.TAGS (post_id, tag_name) VALUES (7, 'LIV');
INSERT INTO BIRDOGIE.TAGS (post_id, tag_name) VALUES (7, 'Question');
INSERT INTO BIRDOGIE.TAGS (post_id, tag_name) VALUES (7, 'Tips');
INSERT INTO BIRDOGIE.TAGS (post_id, tag_name) VALUES (8, 'Equipment');
INSERT INTO BIRDOGIE.TAGS (post_id, tag_name) VALUES (8, 'Rules');
INSERT INTO BIRDOGIE.TAGS (post_id, tag_name) VALUES (9, 'Equipment');
INSERT INTO BIRDOGIE.TAGS (post_id, tag_name) VALUES (9, 'PGA Tour');
INSERT INTO BIRDOGIE.TAGS (post_id, tag_name) VALUES (9, 'Korn Ferry');
INSERT INTO BIRDOGIE.TAGS (post_id, tag_name) VALUES (10, 'Korn Ferry');
INSERT INTO BIRDOGIE.TAGS (post_id, tag_name) VALUES (10, 'Courses');
INSERT INTO BIRDOGIE.TAGS (post_id, tag_name) VALUES (11, 'Rules');
INSERT INTO BIRDOGIE.TAGS (post_id, tag_name) VALUES (11, 'Korn Ferry');
INSERT INTO BIRDOGIE.TAGS (post_id, tag_name) VALUES (12, 'PGA Tour');
INSERT INTO BIRDOGIE.TAGS (post_id, tag_name) VALUES (12, 'Korn Ferry');
INSERT INTO BIRDOGIE.TAGS (post_id, tag_name) VALUES (13, 'Courses');
INSERT INTO BIRDOGIE.TAGS (post_id, tag_name) VALUES (14, 'Korn Ferry');
INSERT INTO BIRDOGIE.TAGS (post_id, tag_name) VALUES (14, 'PGA Tour');
INSERT INTO BIRDOGIE.TAGS (post_id, tag_name) VALUES (15, 'Question');
INSERT INTO BIRDOGIE.TAGS (post_id, tag_name) VALUES (15, 'Korn Ferry');
INSERT INTO BIRDOGIE.TAGS (post_id, tag_name) VALUES (15, 'LIV');
INSERT INTO BIRDOGIE.TAGS (post_id, tag_name) VALUES (16, 'Equipment');
INSERT INTO BIRDOGIE.TAGS (post_id, tag_name) VALUES (16, 'Courses');
INSERT INTO BIRDOGIE.TAGS (post_id, tag_name) VALUES (17, 'Korn Ferry');
INSERT INTO BIRDOGIE.TAGS (post_id, tag_name) VALUES (17, 'LIV');
INSERT INTO BIRDOGIE.TAGS (post_id, tag_name) VALUES (17, 'Courses');
INSERT INTO BIRDOGIE.TAGS (post_id, tag_name) VALUES (18, 'Rules');
INSERT INTO BIRDOGIE.TAGS (post_id, tag_name) VALUES (18, 'Korn Ferry');
INSERT INTO BIRDOGIE.TAGS (post_id, tag_name) VALUES (19, 'Courses');
INSERT INTO BIRDOGIE.TAGS (post_id, tag_name) VALUES (19, 'Rules');
INSERT INTO BIRDOGIE.TAGS (post_id, tag_name) VALUES (19, 'Equipment');
INSERT INTO BIRDOGIE.TAGS (post_id, tag_name) VALUES (20, 'Korn Ferry');
INSERT INTO BIRDOGIE.TAGS (post_id, tag_name) VALUES (20, 'Beginner');
INSERT INTO BIRDOGIE.TAGS (post_id, tag_name) VALUES (21, 'Korn Ferry');
INSERT INTO BIRDOGIE.TAGS (post_id, tag_name) VALUES (22, 'PGA Tour');
INSERT INTO BIRDOGIE.TAGS (post_id, tag_name) VALUES (23, 'PGA Tour');
INSERT INTO BIRDOGIE.TAGS (post_id, tag_name) VALUES (23, 'Question');
INSERT INTO BIRDOGIE.TAGS (post_id, tag_name) VALUES (23, 'Courses');
INSERT INTO BIRDOGIE.TAGS (post_id, tag_name) VALUES (24, 'LIV');
INSERT INTO BIRDOGIE.TAGS (post_id, tag_name) VALUES (24, 'PGA Tour');
INSERT INTO BIRDOGIE.TAGS (post_id, tag_name) VALUES (24, 'Korn Ferry');
INSERT INTO BIRDOGIE.TAGS (post_id, tag_name) VALUES (25, 'Question');
INSERT INTO BIRDOGIE.TAGS (post_id, tag_name) VALUES (25, 'LIV');
INSERT INTO BIRDOGIE.TAGS (post_id, tag_name) VALUES (26, 'LIV');
INSERT INTO BIRDOGIE.TAGS (post_id, tag_name) VALUES (26, 'Tips');
INSERT INTO BIRDOGIE.TAGS (post_id, tag_name) VALUES (26, 'Courses');
INSERT INTO BIRDOGIE.TAGS (post_id, tag_name) VALUES (27, 'LIV');
INSERT INTO BIRDOGIE.TAGS (post_id, tag_name) VALUES (28, 'Courses');
INSERT INTO BIRDOGIE.TAGS (post_id, tag_name) VALUES (28, 'PGA Tour');
INSERT INTO BIRDOGIE.TAGS (post_id, tag_name) VALUES (29, 'Tips');
INSERT INTO BIRDOGIE.TAGS (post_id, tag_name) VALUES (30, 'Tips');
INSERT INTO BIRDOGIE.TAGS (post_id, tag_name) VALUES (30, 'Courses');
INSERT INTO BIRDOGIE.TAGS (post_id, tag_name) VALUES (30, 'PGA Tour');
INSERT INTO BIRDOGIE.TAGS (post_id, tag_name) VALUES (31, 'Equipment');
INSERT INTO BIRDOGIE.TAGS (post_id, tag_name) VALUES (31, 'Tips');
INSERT INTO BIRDOGIE.TAGS (post_id, tag_name) VALUES (31, 'Review');
INSERT INTO BIRDOGIE.TAGS (post_id, tag_name) VALUES (32, 'Rules');
INSERT INTO BIRDOGIE.TAGS (post_id, tag_name) VALUES (32, 'Tips');
INSERT INTO BIRDOGIE.TAGS (post_id, tag_name) VALUES (33, 'Korn Ferry');
INSERT INTO BIRDOGIE.TAGS (post_id, tag_name) VALUES (34, 'Equipment');
INSERT INTO BIRDOGIE.TAGS (post_id, tag_name) VALUES (34, 'Beginner');
INSERT INTO BIRDOGIE.TAGS (post_id, tag_name) VALUES (35, 'PGA Tour');
INSERT INTO BIRDOGIE.TAGS (post_id, tag_name) VALUES (35, 'Tips');
INSERT INTO BIRDOGIE.TAGS (post_id, tag_name) VALUES (35, 'LIV');
INSERT INTO BIRDOGIE.TAGS (post_id, tag_name) VALUES (36, 'PGA Tour');
INSERT INTO BIRDOGIE.TAGS (post_id, tag_name) VALUES (36, 'Question');
INSERT INTO BIRDOGIE.TAGS (post_id, tag_name) VALUES (36, 'LIV');
INSERT INTO BIRDOGIE.TAGS (post_id, tag_name) VALUES (37, 'Courses');
INSERT INTO BIRDOGIE.TAGS (post_id, tag_name) VALUES (37, 'Equipment');
INSERT INTO BIRDOGIE.TAGS (post_id, tag_name) VALUES (37, 'Tips');
INSERT INTO BIRDOGIE.TAGS (post_id, tag_name) VALUES (38, 'Question');
INSERT INTO BIRDOGIE.TAGS (post_id, tag_name) VALUES (38, 'Courses');
INSERT INTO BIRDOGIE.TAGS (post_id, tag_name) VALUES (38, 'Korn Ferry');
INSERT INTO BIRDOGIE.TAGS (post_id, tag_name) VALUES (39, 'Korn Ferry');
INSERT INTO BIRDOGIE.TAGS (post_id, tag_name) VALUES (40, 'Question');
INSERT INTO BIRDOGIE.TAGS (post_id, tag_name) VALUES (40, 'Review');
INSERT INTO BIRDOGIE.TAGS (post_id, tag_name) VALUES (40, 'Equipment');
INSERT INTO BIRDOGIE.TAGS (post_id, tag_name) VALUES (41, 'Korn Ferry');
INSERT INTO BIRDOGIE.TAGS (post_id, tag_name) VALUES (41, 'Equipment');
INSERT INTO BIRDOGIE.TAGS (post_id, tag_name) VALUES (41, 'PGA Tour');
INSERT INTO BIRDOGIE.TAGS (post_id, tag_name) VALUES (42, 'Rules');
INSERT INTO BIRDOGIE.TAGS (post_id, tag_name) VALUES (42, 'Tips');
INSERT INTO BIRDOGIE.TAGS (post_id, tag_name) VALUES (43, 'Korn Ferry');
INSERT INTO BIRDOGIE.TAGS (post_id, tag_name) VALUES (43, 'Tips');
INSERT INTO BIRDOGIE.TAGS (post_id, tag_name) VALUES (44, 'Review');
INSERT INTO BIRDOGIE.TAGS (post_id, tag_name) VALUES (44, 'PGA Tour');
INSERT INTO BIRDOGIE.TAGS (post_id, tag_name) VALUES (45, 'Korn Ferry');
INSERT INTO BIRDOGIE.TAGS (post_id, tag_name) VALUES (46, 'Rules');
INSERT INTO BIRDOGIE.TAGS (post_id, tag_name) VALUES (46, 'Beginner');
INSERT INTO BIRDOGIE.TAGS (post_id, tag_name) VALUES (47, 'Review');
INSERT INTO BIRDOGIE.TAGS (post_id, tag_name) VALUES (47, 'Korn Ferry');
INSERT INTO BIRDOGIE.TAGS (post_id, tag_name) VALUES (48, 'Rules');
INSERT INTO BIRDOGIE.TAGS (post_id, tag_name) VALUES (48, 'Beginner');
INSERT INTO BIRDOGIE.TAGS (post_id, tag_name) VALUES (49, 'Review');
INSERT INTO BIRDOGIE.TAGS (post_id, tag_name) VALUES (50, 'Courses');