DROP SCHEMA BIRDOGIE CASCADE;

CREATE SCHEMA BIRDOGIE;

CREATE TABLE BIRDOGIE.POSTS (id SERIAL, title VARCHAR (1024), tags INTEGER, content VARCHAR(1024), upvotes INTEGER, downvotes INTEGER, poster VARCHAR(255));

CREATE TABLE BIRDOGIE.COMMENTS (id SERIAL, content VARCHAR (1024), upvotes INTEGER, downvotes INTEGER, poster VARCHAR);

CREATE TABLE BIRDOGIE.TAGS (id SERIAL, tag_name VARCHAR(255));
